ALTER TABLE public.listings
  ADD COLUMN IF NOT EXISTS available_quantity integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS condition text NOT NULL DEFAULT 'good',
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';

UPDATE public.listings
SET available_quantity = GREATEST(COALESCE(available_quantity, 1), 0),
    condition = COALESCE(NULLIF(condition, ''), 'good'),
    status = CASE
      WHEN COALESCE(available_quantity, 1) <= 0 THEN 'sold'
      WHEN COALESCE(NULLIF(status, ''), 'active') NOT IN ('active', 'pending', 'sold') THEN 'active'
      ELSE COALESCE(NULLIF(status, ''), 'active')
    END;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'listings_available_quantity_nonnegative'
  ) THEN
    ALTER TABLE public.listings
      ADD CONSTRAINT listings_available_quantity_nonnegative
      CHECK (available_quantity >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'listings_condition_valid'
  ) THEN
    ALTER TABLE public.listings
      ADD CONSTRAINT listings_condition_valid
      CHECK (condition IN ('new', 'like_new', 'good', 'fair', 'poor'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'listings_status_valid'
  ) THEN
    ALTER TABLE public.listings
      ADD CONSTRAINT listings_status_valid
      CHECK (status IN ('active', 'pending', 'sold'));
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.sync_listing_status_from_quantity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.available_quantity <= 0 THEN
    NEW.available_quantity := 0;
    NEW.status := 'sold';
  ELSIF NEW.status = 'sold' THEN
    NEW.status := 'active';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_listing_status_from_quantity ON public.listings;
CREATE TRIGGER trg_sync_listing_status_from_quantity
BEFORE INSERT OR UPDATE OF available_quantity, status
ON public.listings
FOR EACH ROW
EXECUTE FUNCTION public.sync_listing_status_from_quantity();

CREATE TABLE IF NOT EXISTS public.saved_listings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  listing_id bigint NOT NULL REFERENCES public.listings(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, listing_id)
);

CREATE TABLE IF NOT EXISTS public.listing_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  listing_id bigint NOT NULL REFERENCES public.listings(id) ON DELETE CASCADE,
  reason text NOT NULL,
  details text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (char_length(trim(reason)) > 0),
  UNIQUE (reporter_id, listing_id)
);

CREATE INDEX IF NOT EXISTS idx_listings_status_created_desc
  ON public.listings (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_listings_condition_created_desc
  ON public.listings (condition, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_saved_listings_user_created_desc
  ON public.saved_listings (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_saved_listings_listing_id
  ON public.saved_listings (listing_id);

CREATE INDEX IF NOT EXISTS idx_listing_reports_listing_created_desc
  ON public.listing_reports (listing_id, created_at DESC);

ALTER TABLE public.saved_listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_reports ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'saved_listings'
      AND policyname = 'saved_listings_select_own'
  ) THEN
    CREATE POLICY saved_listings_select_own
      ON public.saved_listings
      FOR SELECT
      TO authenticated
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'saved_listings'
      AND policyname = 'saved_listings_insert_own'
  ) THEN
    CREATE POLICY saved_listings_insert_own
      ON public.saved_listings
      FOR INSERT
      TO authenticated
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'saved_listings'
      AND policyname = 'saved_listings_delete_own'
  ) THEN
    CREATE POLICY saved_listings_delete_own
      ON public.saved_listings
      FOR DELETE
      TO authenticated
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'listing_reports'
      AND policyname = 'listing_reports_select_own'
  ) THEN
    CREATE POLICY listing_reports_select_own
      ON public.listing_reports
      FOR SELECT
      TO authenticated
      USING (auth.uid() = reporter_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'listing_reports'
      AND policyname = 'listing_reports_insert_own'
  ) THEN
    CREATE POLICY listing_reports_insert_own
      ON public.listing_reports
      FOR INSERT
      TO authenticated
      WITH CHECK (auth.uid() = reporter_id);
  END IF;
END $$;
